logging:
  level: INFO
  path: ./outputs/logs

paths:
  data: ./data/meds_for_bonsai
  splits: [ train, tuning, held_out ]
  outcomes: ./outputs/outcomes/
  features: ./outputs/features/

outcomes:
  MORTALITY:
    type: [ code ]
    match: [ [ 'DOD' ] ]
    match_how: startswith
    case_sensitive: true
