data:
  type: finetune
  mode: tuning

paths:
  data_dir: ./outputs/tokenized
  cohort: ./outputs/finetuning/cohorts_with_values
  prepared_data: ./outputs/finetuning/processed_data_with_values
  pretrain_model: ./outputs/pretraining_dryrun

biological_features:
  - grim_age_v2
  - systems_age
